### ISSUE TITLE
Solder Mask Feature Error

### ISSUE THREAD

**Issue by ameennihad** [chilipeppr/widget-eagle#26]
I noticed recently that solder mask feature is throwing the following error when reaching the last deflated path of a pad:
`Uncaught TypeError: Cannot read property 'computeBoundingBox' of undefined
    at Object.getCentroid`

The code throwing this error is passing (mesh.children[1]) to getCentroid method, in this method following code is throwing the error:
`mesh.geometry.computeBoundingBox();`
Where mesh is the passed parameter (mesh.children[1]), this parameter has no geometry property, but it has one child of type (mesh.Three) which of course has geometry property.

In current version of the widget, the code works without error, but in my fork and with the updates I did to rending of pads and vias the error is thrown whenever solder mask of full path is executed.

I solved the issue by updating the following code, I'm not sure if this fix will cause further issues, I tested few boards without any noticeable issues or error:

old code: `var centroid = this.getCentroid(mesh.children[1]);`
new code: `var centroid = this.getCentroid(mesh.children[1].children[0]);`

**Comment by chilipeppr** [comment]
That's probably fine. That chunk of code is just looking to move the laser
to the center of the pad to make sure all material is ablated. So, all it's
after is what is the center x/y position of that Three object. Since
there's many different ways to get at a center point, my gut tells me your
way works just fine. So I'd go with it.
